version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.5.0 # Invoke the Codacy Code Coverage orb
  heroku: circleci/heroku@1.2.4 # Invoke the Heroku orb
  
jobs:

  build-and-test:
    docker:
      - image: circleci/node:14.17.1
    steps:
      - checkout
      - restore_cache:
          key: yelpcamp-dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: yelpcamp-dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm run test
      - store_test_results:
          path: ~/junit.xml
      - store_artifacts:
          path: ~/junit.xml

  codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      # run commands to generate the coverage result
      - coverage-reporter/send_report:
          coverage-reports: 'coverage/lcov.info'
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  version: 2
  build_test_deploy:
     jobs:
       - build-and-test
       - codacy-coverage-report
       - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
           requires:
             - build-and-test # only run deploy-via-git job if this job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch